### ISSUE TITLE
Unable to install on M1 Mac

### ISSUE THREAD

**Issue by christippett** [servian/bigquery-view-analyzer#19]
May need to build a wheel or re-pin dependencies with their latest version.

```sh
❯  pipx install bigquery-view-analyzer
    ERROR: Command errored out with exit status 1:
     command: /Users/christippett/.pipx/venvs/bigquery-view-analyzer/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/n9/nr9stx893js0mtqm0bdflm_40000gn/T/pip-install-egmhhns6/grpcio_dc9f50562adb4c27b088a4a1bc5f4ead/setup.py'"'"'; __file__='"'"'/private/var/folders/n9/nr9stx893js0mtqm0bdflm_40000gn/T/pip-install-egmhhns6/grpcio_dc9f50562adb4c27b088a4a1bc5f4ead/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/n9/nr9stx893js0mtqm0bdflm_40000gn/T/pip-pip-egg-info-6cioy2p1
         cwd: /private/var/folders/n9/nr9stx893js0mtqm0bdflm_40000gn/T/pip-install-egmhhns6/grpcio_dc9f50562adb4c27b088a4a1bc5f4ead/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n9/nr9stx893js0mtqm0bdflm_40000gn/T/pip-install-egmhhns6/grpcio_dc9f50562adb4c27b088a4a1bc5f4ead/setup.py", line 359, in <module>
        if mac_target and (pkg_resources.parse_version(mac_target) <
      File "/Users/christippett/.pipx/shared/lib/python3.9/site-packages/pkg_resources/__init__.py", line 114, in parse_version
        return packaging.version.Version(v)
      File "/Users/christippett/.pipx/shared/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    ASM Builds for BoringSSL currently not supported on: macosx-11-arm64
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Error installing bigquery-view-analyzer.
```

**Comment by Marty08** [comment]
Showing off that you got an M1 mac?
